services:
  ns.sentinel.converter.country:
    class: NS\SentinelBundle\Converter\CountryConverter
    arguments: [ "@doctrine.orm.entity_manager"]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.vaccinationreceived:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\Types\VaccinationReceived,'Both' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.site:
    class: NS\SentinelBundle\Converter\SiteConverter
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.triple_choice:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\Types\TripleChoice,'Both' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.gender:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\Types\Gender,'Both' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.meningitisvaccinationreceived:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\Types\VaccinationReceived,'Both' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.threedoses:
    class: NS\SentinelBundle\Converter\DosesConverter
    arguments: [ NS\SentinelBundle\Form\Types\ThreeDoses,'Both' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.fourdoses:
    class: NS\SentinelBundle\Converter\DosesConverter
    arguments: [ NS\SentinelBundle\Form\Types\FourDoses,'Both' ]
    tags:
      - { name: ns_import.converter }

#####################################################################
# IBD
#####################################################################

  ns.sentinel.converter.spnserotype:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\SpnSerotype,'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.serotypeidentifier:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\SerotypeIdentifier,'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.pathogenidentifier:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\PathogenIdentifier, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.pcvtype:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\PCVType, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.pcrresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\PCRResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.otherspecimen:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\OtherSpecimen, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.nmserogroup:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\NmSerogroup, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.meningvaccinationtype:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\VaccinationType, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.latresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\LatResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.isolatetype:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\IsolateType, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.ibdcaseresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\CaseResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.hiserotype:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\HiSerotype, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.gramstainresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\GramStainResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.gramstain:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\GramStain, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.dischargeoutcome:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\DischargeOutcome, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.dischargediagnosis:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\DischargeDiagnosis, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.dischargeclassification:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\DischargeClassification, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.diagnosis:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\Diagnosis, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.cultureresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\CultureResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.casestatus:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\Types\CaseStatus, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.cxrresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\CXRResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.cxradditionalresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\CXRAdditionalResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.binaxresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\BinaxResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.csfappearance:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\CSFAppearance, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.sample_type:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\SampleType, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.isolate_viable:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\IsolateViable, 'IBD' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.finalresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\IBD\Types\FinalResult, 'IBD' ]
    tags:
      - { name: ns_import.converter }

#####################################################################
# IBD
#####################################################################

  ns.sentinel.converter.rotavirusvaccinationtype:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\VaccinationType, 'RV' ]
    tags:
        - { name: ns_import.converter }

  ns.sentinel.converter.genotyperesultp:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\GenotypeResultP, 'RV' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.genotyperesultg:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\GenotypeResultG, 'RV' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.rotavirusdischargeoutcome:
      class: NS\SentinelBundle\Converter\ArrayChoiceConverter
      arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\DischargeOutcome, 'RV' ]
      tags:
        - { name: ns_import.converter }

  ns.sentinel.converter.rotavirusdischargeclassification:
      class: NS\SentinelBundle\Converter\ArrayChoiceConverter
      arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\DischargeClassification, 'RV' ]
      tags:
        - { name: ns_import.converter }

  ns.sentinel.converter.rehydration:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\Rehydration, 'RV' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.elisakit:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\ElisaKit, 'RV' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.elisaresult:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\ElisaResult, 'RV' ]
    tags:
      - { name: ns_import.converter }

  ns.sentinel.converter.dehydration:
    class: NS\SentinelBundle\Converter\ArrayChoiceConverter
    arguments: [ NS\SentinelBundle\Form\RotaVirus\Types\Dehydration, 'RV' ]
    tags:
      - { name: ns_import.converter }

