services:
  ns_sentinel.filter.type.ibd_linking_quarterly:
    class: NS\SentinelBundle\Filter\Type\IBD\QuarterlyLinkingReportFilterType
    arguments: [ @security.context, @ns.security.acl_converter ]
    tags:
      - { name: form.type, alias: QuarterlyLinkingReportFilter }

  ns_sentinel.filter.type.ibd_quarterly:
    class: NS\SentinelBundle\Filter\Type\IBD\QuarterlyReportFilterType
    arguments: [ @security.context, @ns.security.acl_converter ]
    tags:
      - { name: form.type, alias: QuarterlyReportFilter }

  ns_sentinel.filter.type.base_quarterly:
    class: NS\SentinelBundle\Filter\Type\BaseQuarterlyFilterType
    arguments: [ @security.context, @ns.security.acl_converter ]
    tags:
      - { name: form.type, alias: BaseQuarterlyFilter }

  ns.sentinel.form.type.finalresult:
    class: NS\SentinelBundle\Form\Types\FinalResult
    tags:
      - { name: form.type, alias: FinalResult }

  ns.sentinel.form.rota.report_filter:
    class: NS\SentinelBundle\Filter\Type\RotaVirus\FilterType
    arguments: [ @security.context, @ns.security.acl_converter ]
    tags:
      - { name: form.type, alias: RotaVirusReportFilterType }

  ns.sentinel.form.filter.rota.report_filter:
    class: NS\SentinelBundle\Filter\Type\RotaVirus\ReportFilterType
    tags:
      - { name: form.type, alias: RotaVirusReportFilterType }

  ns.sentinel.form.ibd.report_filter:
    class: NS\SentinelBundle\Filter\Type\IBD\ReportFilterType
    tags:
      - { name: form.type, alias: IBDReportFilterType }

  ns.sentinel.form.filters.base_report_filter:
    class: NS\SentinelBundle\Filter\Type\BaseReportFilterType
    arguments: [ @security.context, @ns.security.acl_converter ]
    tags:
      - { name: form.type, alias: BaseReportFilterType }

  ns.sentinel.form.type.ibdintensesupport:
    class: NS\SentinelBundle\Form\Types\IBDIntenseSupport
    tags:
      - { name: form.type, alias: IBDIntenseSupport }

  ns.sentinel.form.type.surveillanceconducted:
    class: NS\SentinelBundle\Form\Types\SurveillanceConducted
    tags:
      - { name: form.type, alias: SurveillanceConducted }

  ns.sentinel.form.type.otherspecimen:
    class: NS\SentinelBundle\Form\Types\OtherSpecimen
    tags:
      - { name: form.type, alias: OtherSpecimen }

  ns.sentinel.form.type.cultureresult:
    class: NS\SentinelBundle\Form\Types\CultureResult
    tags:
      - { name: form.type, alias: CultureResult }

  ns.sentinel.form.type.rotavirusdischargeoutcome:
    class: NS\SentinelBundle\Form\Types\RotavirusDischargeOutcome
    tags:
      - { name: form.type, alias: RotavirusDischargeOutcome }

  ns.sentinel.form.type.pcvtype:
    class: NS\SentinelBundle\Form\Types\PCVType
    tags:
      - { name: form.type, alias: PCVType }

  ns.sentinel.form.type.cxradditionalresult:
    class: NS\SentinelBundle\Form\Types\CXRAdditionalResult
    tags:
      - { name: form.type, alias: CXRAdditionalResult }

  ns.sentinel.form.type.dischargediagnosis:
    class: NS\SentinelBundle\Form\Types\DischargeDiagnosis
    tags:
      - { name: form.type, alias: DischargeDiagnosis }

  ns.sentinel.form.type.threedoses:
    class: NS\SentinelBundle\Form\Types\ThreeDoses
    tags:
      - { name: form.type, alias: ThreeDoses }

  ns.sentinel.form.ibd_outcome:
    class: NS\SentinelBundle\Form\IBD\OutcomeType
    tags:
      - { name: form.type, alias: ibd_outcome }

  ns.sentinel.form.rotavirus_outcome:
    class: NS\SentinelBundle\Form\Rota\OutcomeType
    tags:
      - { name: form.type, alias: rotavirus_outcome }

  ns.sentinel.form.type.spnserotype:
    class: NS\SentinelBundle\Form\Types\SpnSerotype
    tags:
      - { name: form.type, alias: SpnSerotype }

  ns.sentinel.form.type.hiserotype:
    class: NS\SentinelBundle\Form\Types\HiSerotype
    tags:
      - { name: form.type, alias: HiSerotype }

  ns.sentinel.form.type.nmserogroup:
    class: NS\SentinelBundle\Form\Types\NmSerogroup
    tags:
      - { name: form.type, alias: NmSerogroup }

  ns.sentinel.form.type.genotyperesultg:
    class: NS\SentinelBundle\Form\Types\GenotypeResultG
    tags:
      - { name: form.type, alias: GenotypeResultG }

  ns.sentinel.form.type.genotyperesultp:
    class: NS\SentinelBundle\Form\Types\GenotypeResultP
    tags:
      - { name: form.type, alias: GenotypeResultP }

  ns.sentinel.form.filters.lab_filter:
    class: NS\SentinelBundle\Filter\Type\LabFilterType
    tags:
      - { name: form.type, alias: lab_filter }

  ns.sentinel.form.filter.base:
    class: NS\SentinelBundle\Filter\Type\BaseObject
    tags:
      - { name: form.type, alias: filter_object }

  ns.sentinel.form.filter.country:
    class: NS\SentinelBundle\Filter\Type\CountryType
    arguments: [ @doctrine.orm.entity_manager, "NSSentinelBundle:Country" ]
    tags:
      - { name: form.type, alias: country }

  ns.sentinel.form.filter.region:
    class: NS\SentinelBundle\Filter\Type\RegionType
    arguments: [ @doctrine.orm.entity_manager, "NSSentinelBundle:Region" ]
    tags:
      - { name: form.type, alias: region }

  ns.sentinel.form.filter.site:
    class: NS\SentinelBundle\Filter\Type\SiteType
    arguments: [ @doctrine.orm.entity_manager, "NSSentinelBundle:Site" ]
    tags:
      - { name: form.type, alias: site }

  ns.sentinel.form.type.createroles:
    class: NS\SentinelBundle\Form\Types\CreateRoles
    calls:
      - [ setSecurityContext, [ @security.context ] ]
    tags:
      - { name: form.type, alias: CreateRoles }

  ns.sentinel.form.create:
    class: NS\SentinelBundle\Form\CreateType
    arguments: [ "@ns.sentinel.sites", "@doctrine.orm.entity_manager" ]
    tags:
      - { name: form.type, alias: create_case }

  ns.sentinel.form.type.casestatus:
    class: NS\SentinelBundle\Form\Types\CaseStatus
    tags:
      - { name: form.type, alias: CaseStatus }

  ns.sentinel.form.type.dischargeoutcome:
    class: NS\SentinelBundle\Form\Types\DischargeOutcome
    tags:
      - { name: form.type, alias: DischargeOutcome }

  ns.sentinel.form.type.gramstainorganism:
    class: NS\SentinelBundle\Form\Types\GramStainOrganism
    tags:
      - { name: form.type, alias: GramStainOrganism }

  ns.sentinel.form.type.gramstain:
    class: NS\SentinelBundle\Form\Types\GramStain
    tags:
      - { name: form.type, alias: GramStain }

  ns.sentinel.form.type.meningitisvaccinationtype:
    class: NS\SentinelBundle\Form\Types\MeningitisVaccinationType
    tags:
      - { name: form.type, alias: MeningitisVaccinationType }

  ns.sentinel.form.type.vaccinationreceived:
    class: NS\SentinelBundle\Form\Types\VaccinationReceived
    tags:
      - { name: form.type, alias: VaccinationReceived }

  ns.sentinel.form.type.dischargeclassification:
    class: NS\SentinelBundle\Form\Types\DischargeClassification
    tags:
      - { name: form.type, alias: DischargeClassification }

  ns.sentinel.form.type.ibdcaseresult:
    class: NSSentinelBundle\Form\Types\IBDCaseResult
    tags:
      - { name: form.type, alias: IBDCaseResult }

  ns.sentinel.form.type.elisakit:
    class: NS\SentinelBundle\Form\Types\ElisaKit
    tags:
      - { name: form.type, alias: ElisaKit }

  ns.sentinel.form.type.elisaresult:
    class: NS\SentinelBundle\Form\Types\ElisaResult
    tags:
      - { name: form.type, alias: ElisaResult }

  ns.sentinel.form.type.rotavirusvaccinationtype:
    class: NS\SentinelBundle\Form\Types\RotavirusVaccinationType
    tags:
      - { name: form.type, alias: RotavirusVaccinationType }

  ns.sentinel.form.type.rotavirusvaccinationreceived:
    class: NS\SentinelBundle\Form\Types\RotavirusVaccinationReceived
    tags:
      - { name: form.type, alias: RotavirusVaccinationReceived }

  ns.sentinel.form.type.dehydration:
    class: NS\SentinelBundle\Form\Types\Dehydration
    tags:
      - { name: form.type, alias: Dehydration }

  ns.sentinel.form.type.rehydration:
    class: NS\SentinelBundle\Form\Types\Rehydration
    tags:
      - { name: form.type, alias: Rehydration }

  ns.sentinel.form.result_per_page:
    class: NS\SentinelBundle\Form\ResultPerPage
    arguments: [ "ibdIndex" ]
    tags:
      - { name: form.type, alias: results_per_page }

  ns.sentinel.base.filter:
    class: NS\SentinelBundle\Filter\Type\BaseFilterType
    arguments: [ @security.context, @ns.security.acl_converter ]
    tags:
      - { name: form.type, alias: base_filter_form }

  ns.sentinel.rotavirus.filter:
    class: NS\SentinelBundle\Filter\Type\RotaVirus\FilterType
    tags:
      - { name: form.type, alias: rotavirus_filter_form }

  ns.sentinel.meningitis.filter:
    class: NS\SentinelBundle\Filter\Type\IBD\FilterType
    tags:
      - { name: form.type, alias: ibd_filter_form }

  ns.sentinel.form.type.ibd_base:
    class: NS\SentinelBundle\Form\IBD\BaseLabType
    tags:
      - { name: form.type, alias: ibd_base_lab }

  ns.sentinel.form.type.ibd_nl:
    class: NS\SentinelBundle\Form\IBD\NationalLabType
    tags:
      - { name: form.type, alias: ibd_nationallab }

  ns.sentinel.form.type.ibd_rrl:
    class: NS\SentinelBundle\Form\IBD\ReferenceLabType
    tags:
      - { name: form.type, alias: ibd_referencelab }

  ns.sentinel.form.type.ibd_sitelab:
    class: NS\SentinelBundle\Form\IBD\SiteLabType
    arguments: [ "@ns.sentinel.sites" ]
    tags:
      - { name: form.type, alias: ibd_lab }

  ns.sentinel.form.type.ibd:
    class: NS\SentinelBundle\Form\IBD\CaseType
    arguments: [ "@ns.sentinel.sites","@doctrine.orm.entity_manager" ]
    tags:
      - { name: form.type, alias: ibd }

  ns.sentinel.form.type.rota_base:
    class: NS\SentinelBundle\Form\Rota\BaseLabType
    tags:
      - { name: form.type, alias: rotavirus_base_lab }

  ns.sentinel.form.type.rota_nl:
    class: NS\SentinelBundle\Form\Rota\NationalLabType
    tags:
      - { name: form.type, alias: rotavirus_nationallab }

  ns.sentinel.form.type.rota_rrl:
    class: NS\SentinelBundle\Form\Rota\ReferenceLabType
    tags:
      - { name: form.type, alias: rotavirus_referencelab }

  ns.sentinel.form.type.rotavirus_sitelab:
    class: NS\SentinelBundle\Form\Rota\SiteLabType
    arguments: [ "@ns.sentinel.sites" ]
    tags:
      - { name: form.type, alias: rotavirus_lab }

  ns.sentinel.form.type.rotavirus:
    class: NS\SentinelBundle\Form\Rota\CaseType
    arguments: [ "@ns.sentinel.sites", "@doctrine.orm.entity_manager" ]
    tags:
      - { name: form.type, alias: rotavirus }

  ns.sentinel.form.type.pathogenidentifier:
    class: NS\SentinelBundle\Form\Types\PathogenIdentifier
    tags:
      - { name: form.type, alias: PathogenIdentifier }

  ns.sentinel.form.type.serotypeidentifier:
    class: NS\SentinelBundle\Form\Types\SerotypeIdentifier
    tags:
      - { name: form.type, alias: SerotypeIdentifier }

  ns.sentinel.form.type.sampletype:
    class: NS\SentinelBundle\Form\Types\SampleType
    tags:
      - { name: form.type, alias: SampleType }

  ns.sentinel.form.type.isolatetype:
    class: NS\SentinelBundle\Form\Types\IsolateType
    tags:
      - { name: form.type, alias: IsolateType }

  ns.sentinel.form.type.latresult:
    class: NS\SentinelBundle\Form\Types\LatResult
    tags:
      - { name: form.type, alias: LatResult }

  ns.sentinel.form.type.binaxresult:
    class: NS\SentinelBundle\Form\Types\BinaxResult
    tags:
      - { name: form.type, alias: BinaxResult }

  ns.sentinel.form.type.pcrresult:
    class: NS\SentinelBundle\Form\Types\PCRResult
    tags:
      - { name: form.type, alias: PCRResult }

  ns.sentinel.form.type.isolateviable:
    class: NS\SentinelBundle\Form\Types\IsolateViable
    tags:
      - { name: form.type, alias: IsolateViable }

  ns.sentinel.form.type.triple_choice:
    class: NS\SentinelBundle\Form\Types\TripleChoice
    tags:
      - { name: form.type, alias: TripleChoice }

  ns.sentinel.form.type.diagnosis:
    class: NS\SentinelBundle\Form\Types\Diagnosis
    tags:
      - { name: form.type, alias: Diagnosis }

  ns.sentinel.form.type.dischargeClassification:
    class: NS\SentinelBundle\Form\Types\DischargeClassification
    tags:
      - { name: form.type, alias: DischargeClassification }

  ns.sentinel.form.type.dischargeOutcome:
    class: NS\SentinelBundle\Form\Types\DischargeOutcome
    tags:
      - { name: form.type, alias: DischargeOutcome }

  ns.sentinel.form.type.fourdoses:
    class: NS\SentinelBundle\Form\Types\FourDoses
    tags:
      - { name: form.type, alias: FourDoses }

  ns.sentinel.form.type.gender:
    class: NS\SentinelBundle\Form\Types\Gender
    tags:
      - { name: form.type, alias: Gender }

  ns.sentinel.form.type.cxr_result:
    class: NS\SentinelBundle\Form\Types\CXRResult
    tags:
      - { name: form.type, alias: CXRResult }

  ns.sentinel.form.type.CSFAppearance:
    class: NS\SentinelBundle\Form\Types\CSFAppearance
    tags:
      - { name: form.type, alias: CSFAppearance }

  ns.sentinel.form.type.role:
      class: NS\SentinelBundle\Form\Types\Role
      calls:
        - [ setSecurityContext, [ "@security.context" ] ]
      tags:
        - { name: form.type, alias: role }

