services:
  ns_sentinel.validation_group_resolver:
    class: NS\SentinelBundle\Form\ValidatorGroup\ValidatorGroupResolver
    arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]

############################################################################
# Filters
############################################################################
  ns_sentinel.filter.type.rota_linking_quarterly:
    class: NS\SentinelBundle\Filter\Type\RotaVirus\QuarterlyLinkingReportFilterType
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@ns_security.acl_converter" ]
    tags:
      - { name: form.type }

  ns_sentinel.filter.type.ibd_linking_quarterly:
    class: NS\SentinelBundle\Filter\Type\IBD\QuarterlyLinkingReportFilterType
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@ns_security.acl_converter" ]
    tags:
      - { name: form.type }

  ns_sentinel.filter.type.base_quarterly:
    class: NS\SentinelBundle\Filter\Type\BaseQuarterlyFilterType
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@ns_security.acl_converter" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.rota.report_filter:
    class: NS\SentinelBundle\Filter\Type\RotaVirus\FilterType
    tags:
      - { name: form.type }

  ns.sentinel.form.filter.rota.report_filter:
    class: NS\SentinelBundle\Filter\Type\RotaVirus\ReportFilterType
    tags:
      - { name: form.type }

  ns.sentinel.form.ibd.report_filter:
    class: NS\SentinelBundle\Filter\Type\IBD\ReportFilterType
    tags:
      - { name: form.type }

  ns.sentinel.form.filters.base_report_filter:
    class: NS\SentinelBundle\Filter\Type\BaseReportFilterType
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@ns_security.acl_converter" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.filter.country:
    class: NS\SentinelBundle\Filter\Type\CountryType
    arguments: [ "@doctrine.orm.entity_manager", "NSSentinelBundle:Country" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.filter.region:
    class: NS\SentinelBundle\Filter\Type\RegionType
    arguments: [ "@doctrine.orm.entity_manager", "NSSentinelBundle:Region" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.filter.site:
    class: NS\SentinelBundle\Filter\Type\SiteType
    arguments: [ "@doctrine.orm.entity_manager", "NSSentinelBundle:Site" ]
    tags:
      - { name: form.type }

  ns.sentinel.base.filter:
    class: NS\SentinelBundle\Filter\Type\BaseFilterType
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@ns_security.acl_converter" ]
    tags:
      - { name: form.type }

  ns.sentinel.rotavirus.filter:
    class: NS\SentinelBundle\Filter\Type\RotaVirus\FilterType
    tags:
      - { name: form.type }

  ns.sentinel.meningitis.filter:
    class: NS\SentinelBundle\Filter\Type\IBD\FilterType
    tags:
      - { name: form.type }

  ns.sentinel.form.filters.lab_filter:
    class: NS\SentinelBundle\Filter\Type\LabFilterType
    tags:
      - { name: form.type }

  ns_sentinel.form.type.case_creation_type:
    class: NS\SentinelBundle\Form\Types\CaseCreationType
    calls:
      - [ setAuthChecker, [ "@security.authorization_checker" ] ]
    tags:
      - { name: form.type }

  ns.sentinel.form.create:
    class: NS\SentinelBundle\Form\CreateType
    arguments: [ "@ns.sentinel.sites", "@doctrine.orm.entity_manager" ]
    tags:
      - { name: form.type }

############################################################################
# Global Types
############################################################################

  ns.sentinel.form.type.role:
    class: NS\SentinelBundle\Form\Types\Role
    calls:
      - [ setTokenStorage, [ "@security.token_storage" ] ]
    tags:
      - { name: form.type }

  ns.sentinel.form.type.surveillanceconducted:
    class: NS\SentinelBundle\Form\Types\SurveillanceConducted
    tags:
      - { name: form.type }

  ns.sentinel.form.type.vaccinationreceived:
    class: NS\SentinelBundle\Form\Types\VaccinationReceived
    tags:
      - { name: form.type }

  ns.sentinel.form.type.casestatus:
    class: NS\SentinelBundle\Form\Types\CaseStatus
    tags:
      - { name: form.type }

  ns.sentinel.form.type.fourdoses:
    class: NS\SentinelBundle\Form\Types\FourDoses
    tags:
      - { name: form.type }

  ns.sentinel.form.type.gender:
    class: NS\SentinelBundle\Form\Types\Gender
    tags:
      - { name: form.type }

  ns.sentinel.form.type.triple_choice:
    class: NS\SentinelBundle\Form\Types\TripleChoice
    tags:
      - { name: form.type }

############################################################################
# IBD Types
############################################################################
  ns.sentinel.form.type.ibd:
    class: NS\SentinelBundle\Form\IBD\CaseType
    arguments: [ "@ns.sentinel.sites", "@ns_sentinel.validation_group_resolver" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.type.ibd_base:
    class: NS\SentinelBundle\Form\IBD\BaseLabType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.ibd_sitelab:
    class: NS\SentinelBundle\Form\IBD\SiteLabType
    arguments: [ "@ns.sentinel.sites" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.type.ibd_nl:
    class: NS\SentinelBundle\Form\IBD\NationalLabType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.ibd_rrl:
    class: NS\SentinelBundle\Form\IBD\ReferenceLabType
    tags:
      - { name: form.type }

  ns.sentinel.form.ibd_outcome:
    class: NS\SentinelBundle\Form\IBD\OutcomeType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.finalresult:
    class: NS\SentinelBundle\Form\IBD\Types\FinalResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.ibdintensesupport:
    class: NS\SentinelBundle\Form\IBD\Types\IntenseSupport
    tags:
      - { name: form.type }

  ns.sentinel.form.type.otherspecimen:
    class: NS\SentinelBundle\Form\IBD\Types\OtherSpecimen
    tags:
      - { name: form.type }

  ns.sentinel.form.type.cultureresult:
    class: NS\SentinelBundle\Form\IBD\Types\CultureResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.pcvtype:
    class: NS\SentinelBundle\Form\IBD\Types\PCVType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.cxradditionalresult:
    class: NS\SentinelBundle\Form\IBD\Types\CXRAdditionalResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.dischargediagnosis:
    class: NS\SentinelBundle\Form\IBD\Types\DischargeDiagnosis
    tags:
      - { name: form.type }

  ns.sentinel.form.type.threedoses:
    class: NS\SentinelBundle\Form\Types\ThreeDoses
    tags:
      - { name: form.type, alias: ThreeDoses }

  ns.sentinel.form.type.spnserotype:
    class: NS\SentinelBundle\Form\IBD\Types\SpnSerotype
    tags:
      - { name: form.type }

  ns.sentinel.form.type.hiserotype:
    class: NS\SentinelBundle\Form\IBD\Types\HiSerotype
    tags:
      - { name: form.type }

  ns.sentinel.form.type.nmserogroup:
    class: NS\SentinelBundle\Form\IBD\Types\NmSerogroup
    tags:
      - { name: form.type }

  ns.sentinel.form.type.dischargeoutcome:
    class: NS\SentinelBundle\Form\IBD\Types\DischargeOutcome
    tags:
      - { name: form.type }

  ns.sentinel.form.type.gramstain:
    class: NS\SentinelBundle\Form\IBD\Types\GramStain
    tags:
      - { name: form.type }

  ns.sentinel.form.type.gramstain_result:
    class: NS\SentinelBundle\Form\IBD\Types\GramStainResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.meningitisvaccinationtype:
    class: NS\SentinelBundle\Form\IBD\Types\VaccinationType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.dischargeclassification:
    class: NS\SentinelBundle\Form\IBD\Types\DischargeClassification
    tags:
      - { name: form.type }

  ns.sentinel.form.type.ibdcaseresult:
    class: NS\SentinelBundle\Form\IBD\Types\CaseResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.pathogenidentifier:
    class: NS\SentinelBundle\Form\IBD\Types\PathogenIdentifier
    tags:
      - { name: form.type }

  ns.sentinel.form.type.serotypeidentifier:
    class: NS\SentinelBundle\Form\IBD\Types\SerotypeIdentifier
    tags:
      - { name: form.type }

  ns.sentinel.form.type.sampletype:
    class: NS\SentinelBundle\Form\IBD\Types\SampleType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.isolatetype:
    class: NS\SentinelBundle\Form\IBD\Types\IsolateType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.latresult:
    class: NS\SentinelBundle\Form\IBD\Types\LatResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.binaxresult:
    class: NS\SentinelBundle\Form\IBD\Types\BinaxResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.pcrresult:
    class: NS\SentinelBundle\Form\IBD\Types\PCRResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.isolateviable:
    class: NS\SentinelBundle\Form\IBD\Types\IsolateViable
    tags:
      - { name: form.type }

  ns.sentinel.form.type.diagnosis:
    class: NS\SentinelBundle\Form\IBD\Types\Diagnosis
    tags:
      - { name: form.type }

  ns.sentinel.form.type.cxr_result:
    class: NS\SentinelBundle\Form\IBD\Types\CXRResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.csf_appearance:
    class: NS\SentinelBundle\Form\IBD\Types\CSFAppearance
    tags:
      - { name: form.type }

############################################################################
# RotaVirus Types
############################################################################

  ns.sentinel.form.type.rotavirus:
    class: NS\SentinelBundle\Form\RotaVirus\CaseType
    arguments: [ "@ns_sentinel.validation_group_resolver" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.type.rotavirus_sitelab:
    class: NS\SentinelBundle\Form\RotaVirus\SiteLabType
    arguments: [ "@ns.sentinel.sites" ]
    tags:
      - { name: form.type }

  ns.sentinel.form.type.rota_base:
    class: NS\SentinelBundle\Form\RotaVirus\BaseLabType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.rota_nl:
    class: NS\SentinelBundle\Form\RotaVirus\NationalLabType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.rota_rrl:
    class: NS\SentinelBundle\Form\RotaVirus\ReferenceLabType
    tags:
      - { name: form.type }

  ns.sentinel.form.rotavirus_outcome:
    class: NS\SentinelBundle\Form\RotaVirus\OutcomeType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.rotavirusdischargeoutcome:
    class: NS\SentinelBundle\Form\RotaVirus\Types\DischargeOutcome
    tags:
      - { name: form.type }

  ns_sentinel.form.type.rotavirusdischargeclassificataion:
    class: NS\SentinelBundle\Form\RotaVirus\Types\DischargeClassification
    tags:
      - { name: form.type }

  ns.sentinel.form.type.genotyperesultg:
    class: NS\SentinelBundle\Form\RotaVirus\Types\GenotypeResultG
    tags:
      - { name: form.type }

  ns.sentinel.form.type.genotyperesultp:
    class: NS\SentinelBundle\Form\RotaVirus\Types\GenotypeResultP
    tags:
      - { name: form.type }

  ns.sentinel.form.type.elisakit:
    class: NS\SentinelBundle\Form\RotaVirus\Types\ElisaKit
    tags:
      - { name: form.type }

  ns.sentinel.form.type.elisaresult:
    class: NS\SentinelBundle\Form\RotaVirus\Types\ElisaResult
    tags:
      - { name: form.type }

  ns.sentinel.form.type.rotavirusvaccinationtype:
    class: NS\SentinelBundle\Form\RotaVirus\Types\VaccinationType
    tags:
      - { name: form.type }

  ns.sentinel.form.type.dehydration:
    class: NS\SentinelBundle\Form\RotaVirus\Types\Dehydration
    tags:
      - { name: form.type }

  ns.sentinel.form.type.rehydration:
    class: NS\SentinelBundle\Form\RotaVirus\Types\Rehydration
    tags:
      - { name: form.type }
