imports:
    - { resource: converters.yml }
    - { resource: forms.yml }
    - { resource: sonata.yml }
    - { resource: twig.yml }

services:
  ns_sentinel.zero_reporter:
    class: NS\SentinelBundle\Report\ZeroReporter
    arguments: [ "@doctrine.orm.entity_manager" ]

  ns_sentinel.admin.user_validator:
    class: NS\SentinelBundle\Validators\UserAclValidator
    arguments: [ "@security.authorization_checker" ]
    tags:
      - { name: validator.constraint_validator }

  ns_sentinel.loggable_listener:
    class: NS\SentinelBundle\Loggable\LoggableListener
    arguments: [ "@security.token_storage", "@jms_serializer.serializer" ]

  ns_sentinel.exporter:
    class: NS\SentinelBundle\Report\Export\Exporter
    arguments: [ "@twig", "@phpExcel" ]

  ns_sentinel.entity.listener:
    class: NS\SentinelBundle\Entity\Listener\OnFlushListener
    arguments: [ "@ns_sentinel.loggable_listener" ]
    tags:
      - { name: doctrine.event_listener, event: onFlush, method: onFlush }

  ns_sentinel.rotavirus_report:
    class: NS\SentinelBundle\Report\RotaVirusReporter
    arguments: [ "@lexik_form_filter.query_builder_updater", "@doctrine.orm.entity_manager", "@router", "@ns_sentinel.exporter" ]

  ns_sentinel.ibd_report:
    class: NS\SentinelBundle\Report\IBDReporter
    arguments: [ "@lexik_form_filter.query_builder_updater", "@doctrine.orm.entity_manager", "@router", "@ns_sentinel.exporter" ]

  ns.sentinel.services.homepage:
    class: NS\SentinelBundle\Services\Homepage
    arguments: [ "@security.token_storage", "@router" ]

  ns.sentinel.services.login_listener:
    class: NS\SentinelBundle\Services\LoginListener
    arguments: [ "@ns.sentinel.services.homepage", "@event_dispatcher" ]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

  ns_sentinel.locale.guesser:
    class: NS\SentinelBundle\Locale\UserGuesser
    arguments: [ "@lunetics_locale.validator.meta", "@security.token_storage", "@security.authorization_checker" ]
    tags:
      - { name: lunetics_locale.guesser, alias: sentinel_user }

  ns.sentinel.filter.listener:
    class: NS\SentinelBundle\Filter\Listener\CaseAssociationListener
    tags:
      - { name: kernel.event_subscriber }

  ns.sentinel.filter.case_status_listener:
    class: NS\SentinelBundle\Filter\Listener\CaseStatusListener
    tags:
      - { name: kernel.event_subscriber }

  ns.sentinel.filter.case_result_listener:
    class: NS\SentinelBundle\Filter\Listener\CaseResultListener
    tags:
      - { name: kernel.event_subscriber }

  ns.sentinel.sites:
    class: NS\SentinelBundle\Services\SerializedSites
    arguments: [ "@session", "@doctrine.orm.entity_manager" ]

  ns_sentinel.menu_builder:
    class: NS\SentinelBundle\Menu\Builder
    arguments: [ "@knp_menu.factory", "@security.authorization_checker" ]
    tags:
      - { name: knp_menu.menu_builder, method: user, alias: user }
      - { name: knp_menu.menu_builder, method: sidebar, alias: sidebar }

  ns_sentinel.misc_provider:
    class: NS\SentinelBundle\DataFixtures\Alice\MiscProvider
    tags:
      - { name: hautelook_alice.faker.provider }

  ns.sentinel.user_provider:
    class: NS\SentinelBundle\Security\UserProvider
    arguments: [ "@doctrine.orm.entity_manager" ]

  ns_sentinel.object_initializer:
    class: NS\SentinelBundle\Services\ObjectInitializer
    arguments: [ "@doctrine.orm.entity_manager", "@jms_serializer", "@annotations.reader" ]
