services:
  ns_sentinel.current_version:
    class: NS\SentinelBundle\Twig\VersionTwig
    tags:
      - { name: twig.extension }

  ns_sentinel.twig.report.zero_reports:
    class: NS\SentinelBundle\Twig\Report\ZeroReportTwig
    tags:
      - { name: twig.extension }

  ns_sentinel.twig.ct_value:
    class: NS\SentinelBundle\Twig\CTValueExtension
    tags:
      - { name: twig.extension }

  ns.sentinel.twig.case_actions:
    class: NS\SentinelBundle\Twig\CaseActions
    arguments: [ "@security.authorization_checker", "@translator", "@router" ]
    tags:
      - { name: twig.extension }

  ns.sentinel.twig.case_templates:
    class: NS\SentinelBundle\Twig\CaseTemplates
    arguments: [ "@security.authorization_checker", "@twig" ]
    tags:
      - { name: twig.extension }

  ns_sentinel.camel_case_to_snake_case:
    class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter

  ns.sentinel.twig.case_status:
    class: NS\SentinelBundle\Twig\CaseStatus
    arguments: ['@ns_sentinel.cached_validator', '@ns_sentinel.camel_case_to_snake_case']
    tags:
      - { name: twig.extension }

  ns_sentinel.twig.report.site_performance:
    class: NS\SentinelBundle\Twig\Report\SitePerformanceTwig
    arguments: [ "@twig" ]
    tags:
      - { name: twig.extension }

