services:
  ns_sentinel.twig.widgets:
    class: NS\SentinelBundle\Twig\WidgetExtension
    tags:
      - { name: twig.extension }

  ns_sentinel.twig.ct_value:
    class: NS\SentinelBundle\Twig\CTValueExtension
    tags:
      - { name: twig.extension }

  ns.sentinel.twig.case_actions:
    class: NS\SentinelBundle\Twig\CaseActions
    arguments: [ "@security.authorization_checker", "@translator", "@router" ]
    tags:
      - { name: twig.extension }

  ns.sentinel.twig.case_templates:
    class: NS\SentinelBundle\Twig\CaseTemplates
    arguments: [ "@security.authorization_checker", "@twig" ]
    tags:
      - { name: twig.extension }

  ns.sentinel.twig.case_status:
    class: NS\SentinelBundle\Twig\CaseStatus
    tags:
      - { name: twig.extension }

  ns_sentinel.twig.report.site_performance:
    class: NS\SentinelBundle\Twig\Report\SitePerformanceTwig
    arguments: [ "@twig" ]
    tags:
      - { name: twig.extension }
