services:
  - mysql

language: php
php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - composer install -o --prefer-source
  - app/console doctrine:database:create --env=test
  - app/console doctrine:schema:create --env=test
  - app/console doctrine:fixtures:load -n --env=test

script: phpunit -c app

