services:
  - mysql

language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhvm'

before_script:
  - composer self-update
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - composer install -o
  - app/console doctrine:database:drop --env=test --force"
  - app/console doctrine:database:create --env=test"
  - app/console doctrine:schema:create --env=test"
  - app/console doctrine:fixtures:load -n --env=test"
