services:
  - mysql

language: php
php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

before_script:
  - composer self-update
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - composer install -o --prefer-source
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  - bin/console doctrine:fixtures:load -n --env=test

script: vendor/bin/simple-phpunit 

