<?php

namespace NS\SentinelBundle\Repository\Rota;

use \NS\SentinelBundle\Repository\BaseLab;

/**
 * Lab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Lab extends BaseLab
{
    protected $parentClass = 'NSSentinelBundle:RotaVirus';
}
