<?php

namespace NS\SentinelBundle\Repository\Rota;

use NS\SentinelBundle\Repository\BaseLab;

/**
 * NationalLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalLabRepository extends BaseLab
{
    protected $parentClass = 'NSSentinelBundle:RotaVirus';
}
