<?php

namespace NS\SentinelBundle\Repository\Rota;

use NS\SentinelBundle\Repository\BaseLab;

/**
 * ReferenceLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceLab extends BaseLab
{
    protected $parentClass = 'NSSentinelBundle:RotaVirus';
}
