<?php

namespace NS\SentinelBundle\Repository\Rota;

/**
 * SiteLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteLab extends \NS\SentinelBundle\Repository\BaseLab
{
    protected $parentClass = 'NSSentinelBundle:RotaVirus';
}
