<?php

namespace NS\SentinelBundle\Repository\IBD;

use NS\SentinelBundle\Repository\BaseLab;

/**
 * ReferenceLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceLabRepository extends BaseLab
{
    protected $parentClass = 'NSSentinelBundle:IBD';
}
