<?php

namespace NS\SentinelBundle\Repository\IBD;

use \NS\SentinelBundle\Repository\BaseLab;

/**
 * SiteLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteLab extends BaseLab
{
    protected $parentClass = 'NSSentinelBundle:IBD';
}
