<?php

namespace NS\SentinelBundle\Repository;

use NS\SecurityBundle\Doctrine\SecuredEntityRepository;
use NS\UtilBundle\Service\AjaxAutocompleteRepositoryInterface;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\UnexpectedResultException;

/**
 * MeningitisLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseLab extends SecuredEntityRepository implements AjaxAutocompleteRepositoryInterface
{
    protected $parentClass = null;

    public function getForAutoComplete($fields, array $value, $limit)
    {
        $alias = 'd';
        $qb    = $this->createQueryBuilder($alias)->setMaxResults($limit);
        
        if(!empty($value) && $value['value'][0]=='*')
            return $this->secure($qb)->getQuery();
        
        if(!empty($value))
        {
            if(is_array($fields))
            {
                foreach ($fields as $f)
                {
                    $field = "$alias.$f";
                    $qb->addOrderBy($field)
                       ->orWhere("$field LIKE :param")->setParameter('param',$value['value'].'%');
                }
            }
            else
            {
                $field = "$alias.$fields";
                $qb->orderBy($field)->andWhere("$field LIKE :param")->setParameter('param',$value['value'].'%');
            }
        }

        return $this->secure($qb)->getQuery();
    }

    public function findOrCreateNew($id)
    {
        try
        {
            $r = null;

            if(is_numeric($id))
                $r = $this->find($id);
            else
            {
                $qb = $this->createQueryBuilder('r')
                           ->where('r.case = :case')
                           ->setParameter('case',$this->_em->getReference($this->parentClass, $id));

                $r = $this->secure($qb)->getQuery()->getSingleResult();
            }

            if($r)
                return $r;
        }
        catch(UnexpectedResultException $e)
        {
            if($e instanceof NoResultException || $e instanceof NonExistentCase)
            {
                $class  = $this->getClassName();
                $record = new $class();
                $m      = $this->_em->getRepository($this->parentClass)->checkExistence($id);
                $record->setCase($m);

                return $record;
            }

            throw $e;
        }
    }

    public function find($id)
    {
        try
        {
            $qb = $this->createQueryBuilder('m')
                       ->where('m.case = :case')
                       ->setParameter('case', $this->_em->getReference($this->parentClass, $id));

            return $this->secure($qb)->getQuery()->getSingleResult();    
        }
        catch(NoResultException $e)
        {
            throw new NonExistentCase("This case does not exist!");
        }
    }
}
