<?php

namespace NS\SentinelBundle\Repository;

/**
 * NationalLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalLab extends BaseLab
{

}
