<?php

namespace NS\SentinelBundle\Repository;

/**
 * ReferenceLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceLab extends BaseLab
{

}
