<?php

namespace NS\SentinelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MeningitisLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceLab extends EntityRepository
{
}
