<?php

namespace NS\SentinelBundle\Repository;

use NS\SentinelBundle\Repository\Common as CommonRepository;

/**
 * Region
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends CommonRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function getAllForTree()
    {
        return $this->createQueryBuilder('r')
            ->addSelect('c,s')
            ->leftJoin('r.countries', 'c')
            ->leftJoin('c.sites', 's')
            ->getQuery();
    }

    public function getByCountryIds(array $countryIds)
    {
        return $this->createQueryBuilder('r')
            ->innerJoin('r.countries', 'c')
            ->where('c.code IN (:ids)')
            ->setParameter('ids', $countryIds)
            ->getQuery()
            ->getResult();
    }

    public function getBySiteIds(array $siteIds)
    {
        return $this->createQueryBuilder('r')
            ->innerJoin('r.countries', 'c')
            ->innerJoin('c.sites','s')
            ->where('s.code IN (:ids)')
            ->setParameter('ids', $siteIds)
            ->getQuery()
            ->getResult();
    }
}
