<?php

namespace NS\SentinelBundle\Repository;

use NS\SentinelBundle\Repository\Common as CommonRepository;

/**
 * Region
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Region extends CommonRepository
{
    public function getAllForTree()
    {
        return $this->_em
                    ->createQuery("SELECT r,c,s FROM ".$this->getClassName()." r LEFT JOIN r.countries c LEFT JOIN c.sites s");
    }
}
