parameters:
#    ns_sonata.example.class: NS\SonataBundle\Example

services:
#    ns_sonata.example:
#        class: %ns_sonata.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
