imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: '%kernel.debug%'
    form:            ~
    csrf_protection: false #TODO this needs to be fixed - FOSRestBundle isn't working without this setting
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    session:
      name: WorldHealthOrganizationSentinelNetwork
      save_path: /tmp/nuvi
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
      resources:
        - 'NSUtilBundle:Form:fields.html.twig'
        - 'NSAceBundle:Form:fields.html.twig'
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            TripleChoice: NS\SentinelBundle\Entity\Types\TripleChoice
            Doses: NS\SentinelBundle\Entity\Types\Doses
            Diagnosis: NS\SentinelBundle\Entity\Types\Diagnosis
            CXRResult: NS\SentinelBundle\Entity\Types\CXRResult
            DischargeClassification: NS\SentinelBundle\Entity\Types\DischargeClassification
            CSFAppearance: NS\SentinelBundle\Entity\Types\CSFAppearance
            Role: NS\SentinelBundle\Entity\Types\Role
            Gender: NS\SentinelBundle\Entity\Types\Gender
            BinaxResult: NS\SentinelBundle\Entity\Types\BinaxResult
            LatResult: NS\SentinelBundle\Entity\Types\LatResult
            PCRResult: NS\SentinelBundle\Entity\Types\PCRResult
            GramStain: NS\SentinelBundle\Entity\Types\GramStain
            GramStainOrganism: NS\SentinelBundle\Entity\Types\GramStainOrganism
            IsolateType: NS\SentinelBundle\Entity\Types\IsolateType
            Volume: NS\SentinelBundle\Entity\Types\Volume
            SerotypeIdentifier: NS\SentinelBundle\Entity\Types\SerotypeIdentifier
            PathogenIdentifier: NS\SentinelBundle\Entity\Types\PathogenIdentifier
            Rehydration: NS\SentinelBundle\Entity\Types\Rehydration
            Dehydration: NS\SentinelBundle\Entity\Types\Dehydration
            RotavirusVaccinationReceived: NS\SentinelBundle\Entity\Types\RotavirusVaccinationReceived
            RotavirusVaccinationType: NS\SentinelBundle\Entity\Types\RotavirusVaccinationType
            ElisaResult: NS\SentinelBundle\Entity\Types\ElisaResult
            IBDCaseResult: NS\SentinelBundle\Entity\Types\IBDCaseResult
            VaccinationReceived: NS\SentinelBundle\Entity\Types\VaccinationReceived
            MeningitisVaccinationType:  NS\SentinelBundle\Entity\Types\MeningitisVaccinationType
            DischargeClassification: NS\SentinelBundle\Entity\Types\DischargeClassification
            DischargeOutcome: NS\SentinelBundle\Entity\Types\DischargeOutcome
            CaseStatus: NS\SentinelBundle\Entity\Types\CaseStatus
            IBDCreateRoles: NS\SentinelBundle\Entity\Types\IBDCreateRoles
            GenotypeResultG: NS\SentinelBundle\Entity\Types\GenotypeResultG
            GenotypeResultP: NS\SentinelBundle\Entity\Types\GenotypeResultP
            NmSerogroup: NS\SentinelBundle\Entity\Types\NmSerogroup
            HiSerotype: NS\SentinelBundle\Entity\Types\HiSerotype
            SpnSerotype: NS\SentinelBundle\Entity\Types\SpnSerotype
            RotavirusDoses: NS\SentinelBundle\Entity\Types\RotavirusDoses
            DischargeDiagnosis: NS\SentinelBundle\Entity\Types\DischargeDiagnosis
            CXRAdditionalResult: NS\SentinelBundle\Entity\Types\CXRAdditionalResult
            PCVType: NS\SentinelBundle\Entity\Types\PCVType
            RotavirusDischargeOutcome: NS\SentinelBundle\Entity\Types\RotavirusDischargeOutcome
            CultureResult: NS\SentinelBundle\Entity\Types\CultureResult
            ElisaKit: NS\SentinelBundle\Entity\Types\ElisaKit
            OtherSpecimen: NS\SentinelBundle\Entity\Types\OtherSpecimen
            SurveillanceConducted: NS\SentinelBundle\Entity\Types\SurveillanceConducted
        mapping_types:
            TripleChoice: TripleChoice
            Doses: Doses
            Diagnosis: Diagnosis
            CXRResult: CXRResult
            DischargeClassification: DischargeClassification
            CSFAppearance: CSFAppearance
            Role: Role
            Gender: Gender
            BinaxResult: BinaxResult
            LatResult: LatResult
            PCRResult: PCRResult
            GramStain: GramStain
            IsolateType: IsolateType
            Volume: Volume
            SerotypeIdentifier: SerotypeIdentifier
            PathogenIdentifier: PathogenIdentifier
            Rehydration: Rehydration
            Dehydration: Dehydration
            RotavirusVaccinationReceived: RotavirusVaccinationReceived
            RotavirusVaccinationType: RotavirusVaccinationType
            ElisaResult: ElisaResult
            IBDCaseResult: IBDCaseResult
            VaccinationReceived: VaccinationReceived
            MeningitisVaccinationType: MeningitisVaccinationType
            GramStainOrganism: GramStainOrganism
            DischargeClassification: DischargeClassification
            DischargeOutcome: DischargeOutcome
            CaseStatus: CaseStatus
            IBDCreateRoles: IBDCreateRoles
            GenotypeResultG: GenotypeResultG
            GenotypeResultP: GenotypeResultP
            NmSerogroup: NmSerogroup
            HiSerotype: HiSerotype
            SpnSerotype: SpnSerotype
            RotavirusDoses: RotavirusDoses
            DischargeDiagnosis: DischargeDiagnosis
            CXRAdditionalResult: CXRAdditionalResult
            PCVType: PCVType
            RotavirusDischargeOutcome: RotavirusDischargeOutcome
            CultureResult: CultureResult
            ElisaKit: ElisaKit
            OtherSpecimen: OtherSpecimen
            SurveillanceConducted: SurveillanceConducted
            
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
          loggable:
            type: annotation
            alias: Gedmo
            prefix: Gedmo\Loggable\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: NSAceBundle:Menu:menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

sonata_admin:
    title:      NUVI Sentinel Network Administration
    templates:
        layout: NSSentinelBundle:Sonata:layout.html.twig
        pager_links: NSSentinelBundle:Sonata:pager.html.twig

sonata_doctrine_orm_admin:
  templates:
    form:
      - NSUtilBundle:Form:SonataDoctrineORM/form_admin_fields.html.twig

jms_serializer:
    property_naming:
        separator:  ~
        lower_case: false

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"

jms_translation:
  locales: %locales%
  configs:
    sentinel:
      output_dir: %kernel.root_dir%/../src/NS/SentinelBundle/Resources/translations        
      dirs: [ "%kernel.root_dir%/../src/NS/SentinelBundle" ]
      excluded_names: [ "*TestCase.php", "*Test.php" ]
      excluded_dirs: [ cache, data, logs, Features ]
      output_format: xliff

knp_paginator:
  template:
    pagination: NSAceBundle:Form:pagination.html.twig

lunetics_locale:
    strict_mode: true
    guessing_order:
        - router
        - cookie
        - browser
    allowed_locales: %locales%
    switcher:
        show_current_locale: true

fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        NS\ApiBundle\Entity\Client
    access_token_class:  NS\ApiBundle\Entity\AccessToken
    refresh_token_class: NS\ApiBundle\Entity\RefreshToken
    auth_code_class:     NS\ApiBundle\Entity\AuthCode
    service:
        user_provider: ns.sentinel.user_provider

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
#    request: { converters: true }
    
fos_rest:
    param_fetcher_listener: true
    format_listener: true
    view:
        view_response_listener: true
        formats:
            json: true
            xml:  true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml ], fallback_format: false, prefer_extension: true }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }

    disable_csrf_role: ROLE_API
    exception:
      codes:
        'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
        '\NS\SentinelBundle\Exceptions\NonExistentCase': 404

nelmio_api_doc:
  name: WHO API Documentation
  sandbox:
    accept_type: application/json
    request_format:
      method: accept_header
      default_format: json
    authentication:
      delivery: header
      name: Authorization
    body_format: json

ns_import:
  classes: { NS\SentinelBundle\Entity\IBD: IBD, NS\SentinelBundle\Entity\Rotavirus: Rotavirus }

services:
  ns.form.types.autocomplete:
    class: NS\UtilBundle\Form\Types\Autocomplete
    arguments: [ "@doctrine.orm.entity_manager", "@router" ]
    tags:
      - { name: form.type, alias: ns_autocomplete }
  ns.ajax_autocompleter:
    class: NS\UtilBundle\Service\Ajax
    arguments: [ "@doctrine.orm.entity_manager", "@request", "@templating" ]
    scope: request
  twig.text_extension:
    class: Twig_Extensions_Extension_Text
    tags:
      - name: twig.extension
  extension.listener:
    class: NS\SentinelBundle\Listeners\DoctrineExtensionListener
    calls:
      - [ setContainer, [ @service_container ] ]
    tags:
      # loggable hooks user username if one is in security context
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  gedmo.listener.loggable:
    class: Gedmo\Loggable\LoggableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ @annotation_reader ] ]
