imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: '%kernel.debug%'
    form:            ~
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    session:
      name: WorldHealthOrganizationSentinelNetwork
      save_path: /tmp/nuvi
      cookie_httponly: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
      resources:
        - NSUtilBundle:Form:fields.html.twig
        - NSAceBundle:Form:fields.html.twig
        - NSSentinelBundle::form_fields.html.twig
        - NSImportBundle::form_fields.html.twig
        - VichUploaderBundle:Form:fields.html.twig
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        server_version: 5.1
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     "%database_path%"
        types:
            TripleChoice: NS\SentinelBundle\Entity\Types\TripleChoice
            FourDoses: NS\SentinelBundle\Entity\Types\FourDoses
            Role: NS\SentinelBundle\Entity\Types\Role
            Gender: NS\SentinelBundle\Entity\Types\Gender
            SurveillanceConducted: NS\SentinelBundle\Entity\Types\SurveillanceConducted
            CaseStatus: NS\SentinelBundle\Entity\Types\CaseStatus
            ThreeDoses: NS\SentinelBundle\Entity\Types\ThreeDoses
            VaccinationReceived: NS\SentinelBundle\Entity\Types\VaccinationReceived

            BinaxResult: NS\SentinelBundle\Entity\IBD\Types\BinaxResult
            CaseResult: NS\SentinelBundle\Entity\IBD\Types\CaseResult
            CSFAppearance: NS\SentinelBundle\Entity\IBD\Types\CSFAppearance
            CultureResult: NS\SentinelBundle\Entity\IBD\Types\CultureResult
            CXRAdditionalResult: NS\SentinelBundle\Entity\IBD\Types\CXRAdditionalResult
            CXRResult: NS\SentinelBundle\Entity\IBD\Types\CXRResult
            Diagnosis: NS\SentinelBundle\Entity\IBD\Types\Diagnosis
            IBDDischargeClassification: NS\SentinelBundle\Entity\IBD\Types\DischargeClassification
            IBDDischargeDiagnosis: NS\SentinelBundle\Entity\IBD\Types\DischargeDiagnosis
            IBDDischargeOutcome: NS\SentinelBundle\Entity\IBD\Types\DischargeOutcome
            FinalResult: NS\SentinelBundle\Entity\IBD\Types\FinalResult
            GramStain: NS\SentinelBundle\Entity\IBD\Types\GramStain
            GramStainResult: NS\SentinelBundle\Entity\IBD\Types\GramStainResult
            HiSerotype: NS\SentinelBundle\Entity\IBD\Types\HiSerotype
            IntenseSupport: NS\SentinelBundle\Entity\IBD\Types\IntenseSupport
            IsolateType: NS\SentinelBundle\Entity\IBD\Types\IsolateType
            IsolateViable: NS\SentinelBundle\Entity\IBD\Types\IsolateViable
            LatResult: NS\SentinelBundle\Entity\IBD\Types\LatResult
            NmSerogroup: NS\SentinelBundle\Entity\IBD\Types\NmSerogroup
            OtherSpecimen: NS\SentinelBundle\Entity\IBD\Types\OtherSpecimen
            PathogenIdentifier: NS\SentinelBundle\Entity\IBD\Types\PathogenIdentifier
            PCRResult: NS\SentinelBundle\Entity\IBD\Types\PCRResult
            PCVType: NS\SentinelBundle\Entity\IBD\Types\PCVType
            SampleType: NS\SentinelBundle\Entity\IBD\Types\SampleType
            SerotypeIdentifier: NS\SentinelBundle\Entity\IBD\Types\SerotypeIdentifier
            SpnSerotype: NS\SentinelBundle\Entity\IBD\Types\SpnSerotype
            IBDVaccinationType:  NS\SentinelBundle\Entity\IBD\Types\VaccinationType

            Rehydration: NS\SentinelBundle\Entity\RotaVirus\Types\Rehydration
            Dehydration: NS\SentinelBundle\Entity\RotaVirus\Types\Dehydration
            GenotypeResultG: NS\SentinelBundle\Entity\RotaVirus\Types\GenotypeResultG
            GenotypeResultP: NS\SentinelBundle\Entity\RotaVirus\Types\GenotypeResultP
            RVVaccinationType: NS\SentinelBundle\Entity\RotaVirus\Types\VaccinationType
            RVDischargeOutcome: NS\SentinelBundle\Entity\RotaVirus\Types\DischargeOutcome
            RVDischargeClassification: NS\SentinelBundle\Entity\RotaVirus\Types\DischargeClassification
            ElisaKit: NS\SentinelBundle\Entity\RotaVirus\Types\ElisaKit
            ElisaResult: NS\SentinelBundle\Entity\RotaVirus\Types\ElisaResult

            #Depricated
#            GramStainOrganism: NS\SentinelBundle\Entity\Types\GramStainOrganism

#            MeningitisVaccinationType: NS\SentinelBundle\Entity\IBD\Types\VaccinationType
#            DischargeOutcome: NS\SentinelBundle\Entity\IBD\Types\DischargeOutcome
#            DischargeClassification: NS\SentinelBundle\Entity\IBD\Types\DischargeClassification
#            DischargeDiagnosis: NS\SentinelBundle\Entity\IBD\Types\DischargeDiagnosis
#            IBDCaseResult: NS\SentinelBundle\Entity\IBD\Types\CaseResult
#            RotavirusVaccinationReceived: NS\SentinelBundle\Entity\Types\VaccinationReceived
#            RotavirusVaccinationType: NS\SentinelBundle\Entity\RotaVirus\Types\VaccinationType
#            RotavirusDischargeOutcome: NS\SentinelBundle\Entity\RotaVirus\Types\DischargeOutcome
#            RotaVirusDischargeClassification: NS\SentinelBundle\Entity\RotaVirus\Types\DischargeClassification
#            IBDIntenseSupport: NS\SentinelBundle\Entity\IBD\Types\IntenseSupport

        mapping_types:
            TripleChoice: TripleChoice
            Role: Role
            Gender: Gender
            FourDoses: FourDoses
            ThreeDoses: ThreeDoses
            SurveillanceConducted: SurveillanceConducted
            CaseStatus: CaseStatus
            VaccinationReceived: VaccinationReceived

#            GramStainOrganism: GramStainOrganism

            BinaxResult: BinaxResult
            CaseResult: CaseResult
            CSFAppearance: CSFAppearance
            CultureResult: CultureResult
            CXRAdditionalResult: CXRAdditionalResult
            CXRResult: CXRResult
            Diagnosis: Diagnosis
            IBDDischargeClassification: IBDDischargeClassification
            IBDDischargeDiagnosis: IBDDischargeDiagnosis
            IBDDischargeOutcome: IBDDischargeOutcome
            FinalResult: FinalResult
            GramStain: GramStain
            GramStainResult: GramStainResult
            HiSerotype: HiSerotype
            IntenseSupport: IntenseSupport
            IsolateType: IsolateType
            IsolateViable: IsolateViable
            LatResult: LatResult
            NmSerogroup: NmSerogroup
            OtherSpecimen: OtherSpecimen
            PathogenIdentifier: PathogenIdentifier
            PCRResult: PCRResult
            PCVType: PCVType
            SampleType: SampleType
            SerotypeIdentifier: SerotypeIdentifier
            SpnSerotype: SpnSerotype
            IBDVaccinationType: IBDVaccinationType

            Rehydration: Rehydration
            GenotypeResultG: GenotypeResultG
            GenotypeResultP: GenotypeResultP
            RVaccinationType: RVVaccinationType
            Dehydration: Dehydration
            ElisaResult: ElisaResult
            ElisaKit: ElisaKit
            RVDischargeOutcome: RVDischargeOutcome
            RVDischargeClassification: RVDischargeClassification
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
          loggable:
            type: annotation
            alias: Gedmo
            prefix: Gedmo\Loggable\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: NSAceBundle:Menu:menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

sonata_admin:
    title:      NUVI Sentinel Network Administration

jms_serializer:
    property_naming:
        separator:  ~
        lower_case: true

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"

jms_translation:
  locales: "%locales%"
  configs:
    app:
      output_dir: "%kernel.root_dir%/Resources/translations"
      dirs: [ "%kernel.root_dir%" ]
      excluded_names: [ "*TestCase.php", "*Test.php", "bootstrap.php.cache" ]
      excluded_dirs: [ cache, data, logs ]
      output_format: xliff
    sentinel:
      output_dir: "%kernel.root_dir%/../src/NS/SentinelBundle/Resources/translations"
      dirs: [ "%kernel.root_dir%/../src/NS/SentinelBundle" ]
      excluded_names: [ "*TestCase.php", "*Test.php" ]
      excluded_dirs: [ Tests ]
      output_format: xliff
    import:
      output_dir: "%kernel.root_dir%/../src/NS/ImportBundle/Resources/translations"
      dirs: [ "%kernel.root_dir%/../src/NS/ImportBundle"]
      excluded_names: [ "*TestCase.php", "*Test.php" ]
      excluded_dirs: [ Tests ]
      output_format: xliff
    api:
      output_dir: "%kernel.root_dir%/../src/NS/ApiBundle/Resources/translations"
      dirs: [ "%kernel.root_dir%/../src/NS/ApiBundle" ]
      excluded_names: [ "Test","*TestCase.php", "*Test.php" ]
      excluded_dirs: [ Tests ]
      output_format: xliff

knp_paginator:
  template:
    pagination: NSAceBundle:Form:pagination.html.twig

lunetics_locale:
  strict_mode: true
  guessing_order:
    - router
    - cookie
    - sentinel_user
    - browser
  allowed_locales: "%locales%"
  switcher:
    show_current_locale: true

fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        NS\ApiBundle\Entity\Client
    access_token_class:  NS\ApiBundle\Entity\AccessToken
    refresh_token_class: NS\ApiBundle\Entity\RefreshToken
    auth_code_class:     NS\ApiBundle\Entity\AuthCode
    service:
      user_provider: ns.sentinel.user_provider

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
#    request: { converters: true }
    
fos_rest:
    param_fetcher_listener: true
    serializer:
        serialize_null: true
    view:
        view_response_listener: true
        formats:
            json: true
            xml:  true
        templating_formats:
            html: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/api, priorities: [ json, xml ], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    disable_csrf_role: ROLE_API
    exception:
      codes:
        '\Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
        '\NS\SentinelBundle\Exceptions\NonExistentCaseException': 404

nelmio_api_doc:
  name: WHO API Documentation
  sandbox:
    accept_type: application/json
    request_format:
      method: accept_header
      default_format: json
    authentication:
      delivery: header
      name: Authorization
    body_format: json

ns_import:
  classes:
    NS\SentinelBundle\Entity\IBD: IBD
    NS\SentinelBundle\Entity\RotaVirus: Rotavirus

doctrine_cache:
    providers:
        my_phpfile_cache:
            type: php_file

vich_uploader:
    db_driver: orm

    mappings:
        import_file:
            uri_prefix:         /imports/files
            upload_destination: "%kernel.root_dir%/data/imports/files"
            directory_namer:    ns_import.vich.directory_namer
            inject_on_load:     true

leezy_pheanstalk:
    pheanstalks:
        primary:
            server: "%beanstalk_server%"
            default: true

services:
  extension.listener:
    class: NS\SentinelBundle\Listeners\LoggableListener
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@gedmo.listener.loggable" ]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  twig.text_extension:
    class: Twig_Extensions_Extension_Text
    tags:
      - name: twig.extension

  gedmo.listener.loggable:
    class: Gedmo\Loggable\LoggableListener
    tags:
      - { name: doctrine.event_subscriber, connection: default }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]
