parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: whotest
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b329430c-f21a-4e34-ac0b-535abd3a63b1
    locales:
        - en
        - fr
        - es
        - hi
        - pt
