home_redirect:
    path: /
    defaults:
        _controller: 'NSSentinelBundle:Security:homepageRedirect'

login_check:
    path: /login_check

logout:
    path: /logout

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans

admin:
     resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
     prefix: /{_locale}/admin

_sonata_admin:
     resource: .
     type: sonata_admin
     prefix: /{_locale}/admin

ns_api:
    resource: "@NSApiBundle/Resources/config/routing.yml"
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/doc/api

ns_import:
    resource: "@NSImportBundle/Resources/config/routing.yml"
    prefix:   /

ns_sentinel:
    resource: "@NSSentinelBundle/Resources/config/routing.yml"
    prefix:   /
