home_redirect:
    pattern: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: homepage
        statusCode: 301
        useReferrer: false

login_check:
    pattern: /login_check

logout:
    pattern: /logout

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans

admin:
     resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
     prefix: /{_locale}/admin

_sonata_admin:
     resource: .
     type: sonata_admin
     prefix: /{_locale}/admin

ns_api:
    resource: "@NSApiBundle/Controller"
    prefix:   /oauth/v2/auth
    type:     annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#api_login_auth:
#    pattern: /oauth/v2/auth
#    defaults: { _controller: 'FOSOAuthServerBundle:Authorize:authorize' }

#api_login:
#    pattern: /oauth/v2/auth/login
#    defaults: { _controller: 'NSApiBundle:Security:login' }

#api_login_check:
#    pattern: /oauth/v2/auth/login_check
#    defaults: { _controller: 'NSApiBundle:Security:loginCheck' }

ns_api:
    resource: "@NSApiBundle/Resources/config/routing.yml"
    prefix:   /

ns_sentinel:
    resource: "@NSSentinelBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc