security:
    encoders:
        NS\SentinelBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_CAN_CREATE_CASE: ROLE_CAN_CREATE
        ROLE_CAN_CREATE_RRL_LAB: ROLE_CAN_CREATE
        ROLE_CAN_CREATE_NL_LAB: ROLE_CAN_CREATE
        ROLE_CAN_CREATE_LAB: ROLE_CAN_CREATE
        ROLE_SITE:        [ ROLE_USER, ROLE_CAN_CREATE_CASE, ROLE_CAN_SEE_LAB, ROLE_CAN_SEE_RRL, ROLE_CAN_SEE_NL ]
        ROLE_LAB:         [ ROLE_USER, ROLE_CAN_CREATE_LAB, ROLE_CAN_SEE_LAB ]
        ROLE_RRL_LAB:     [ ROLE_USER, ROLE_CAN_CREATE_RRL_LAB, ROLE_CAN_SEE_RRL, ROLE_CAN_CHANGE_LANGUAGE ]
        ROLE_NL_LAB:      [ ROLE_USER, ROLE_CAN_CREATE_NL_LAB, ROLE_CAN_SEE_NL, ROLE_CAN_CHANGE_LANGUAGE ]
        ROLE_COUNTRY:     [ ROLE_USER, ROLE_CAN_SEE_LAB, ROLE_CAN_SEE_RRL, ROLE_CAN_SEE_NL, ROLE_CAN_CHANGE_LANGUAGE ]
        ROLE_REGION:      [ ROLE_USER, ROLE_CAN_SEE_LAB, ROLE_CAN_SEE_RRL, ROLE_CAN_SEE_NL, ROLE_CAN_CHANGE_LANGUAGE ]
        ROLE_ADMIN:       [ ROLE_USER, ROLE_CAN_CHANGE_LANGUAGE ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        users:
            id: ns.sentinel.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: ~

        secured_area:
            pattern:    ^/
            admin-login:
                check_path: /login_check
                login_path: /login
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
            switch_user: true

    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_trans, roles: ROLE_ADMIN }
        - { path: ^/[^/]+/import, roles: ROLE_ADMIN }
        - { path: '^/[^/]+/admin', roles: ROLE_ADMIN }
        - { path: '^/[^/]+/ibd/edit', roles: ROLE_CAN_CREATE_CASE }
        - { path: '^/[^/]+/ibd/create', roles: ROLE_CAN_CREATE }
        - { path: '^/[^/]+/ibd/rrl', roles: [ ROLE_RRL_LAB, ROLE_CAN_CREATE_RRL_LAB ] }
        - { path: '^/[^/]+/ibd/lab', roles: [ ROLE_LAB, ROLE_CAN_CREATE_LAB ] }
        - { path: '^/[^/]+/ibd/nl', roles: [ ROLE_LAB, ROLE_CAN_CREATE_NL_LAB ] }
        - { path: '^/[^/]+/ibd/show', roles: [ ROLE_REGION, ROLE_COUNTRY, ROLE_SITE, ROLE_LAB, ROLE_RRL_LAB, ROLE_NL_LAB ] }
        - { path: '^/[^/]+/rota/edit', roles: ROLE_CAN_CREATE_CASE }
        - { path: '^/[^/]+/rota/create', roles: ROLE_CAN_CREATE }
        - { path: '^/[^/]+/rota/rrl', roles: [ ROLE_RRL_LAB, ROLE_CAN_CREATE_RRL_LAB ] }
        - { path: '^/[^/]+/rota/lab', roles: [ ROLE_LAB, ROLE_CAN_CREATE_LAB ] }
        - { path: '^/[^/]+/rota/nl', roles: [ ROLE_LAB, ROLE_CAN_CREATE_NL_LAB ] }
        - { path: '^/[^/]+/rota/show', roles: [ ROLE_REGION, ROLE_COUNTRY, ROLE_SITE, ROLE_LAB, ROLE_RRL_LAB, ROLE_NL_LAB ] }
        - { path: ^/, roles: ROLE_USER }
