security:
    encoders:
        NS\SentinelBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SITE:        [ ROLE_USER, ROLE_CAN_CREATE_CASE ]
        ROLE_LAB:         [ ROLE_USER, ROLE_CAN_CREATE_LAB ]
        ROLE_RRL_LAB:     [ ROLE_USER, ROLE_CAN_CREATE_RRL_LAB ]
        ROLE_COUNTRY:     ROLE_USER
        ROLE_REGION:      ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            id: ns.sentinel.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: ~

        secured_area:
            pattern:    ^/
            admin-login:
                check_path: /login_check
                login_path: /login
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
            switch_user: true

    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_trans, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: '^/[^/]+/ibd/edit', roles: ROLE_CAN_CREATE_CASE }
        - { path: '^/[^/]+/ibd/create', roles: ROLE_CAN_CREATE_CASE }
        - { path: '^/[^/]+/ibd/rrl', roles: [ ROLE_RRL_LAB, ROLE_CAN_CREATE_RRL_LAB ] }
        - { path: '^/[^/]+/ibd/lab', roles: [ ROLE_LAB, ROLE_CAN_CREATE_LAB ] }
        - { path: '^/[^/]+/ibd/show', roles: [ ROLE_REGION, ROLE_COUNTRY, ROLE_SITE, ROLE_LAB, ROLE_RRL_LAB ] }
        - { path: ^/, roles: ROLE_USER }
