security:
    encoders:
        NS\SentinelBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_CAN_CREATE_CASE: ROLE_CAN_CREATE
        ROLE_CAN_CREATE_LAB: ROLE_CAN_CREATE
        ROLE_SITE:        [ ROLE_USER, ROLE_CAN_CREATE_CASE, ROLE_CAN_SEE_LAB ]
        ROLE_LAB:         [ ROLE_USER, ROLE_CAN_CREATE_LAB, ROLE_CAN_SEE_LAB ]
        ROLE_COUNTRY:     [ ROLE_USER, ROLE_CAN_SEE_LAB, ROLE_CAN_CHANGE_LANGUAGE ]
        ROLE_REGION:      [ ROLE_USER, ROLE_CAN_SEE_LAB, ROLE_CAN_CHANGE_LANGUAGE ]
        ROLE_ADMIN:       [ ROLE_USER, ROLE_CAN_CHANGE_LANGUAGE, ROLE_IMPORT ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_REGION_API:  ROLE_API
        ROLE_COUNTRY_API: ROLE_API
        ROLE_SITE_API:    ROLE_API

    providers:
        users:
            id: ns.sentinel.user_provider

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false

        oauth_login:
            pattern:    ^/oauth/v2/auth/login$
            security:   false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            # Add your favorite authentication process here
            form-login:
                check_path: /oauth/v2/auth/login_check
                login_path: /oauth/v2/auth/login
                use_referer: true

        login:
            pattern:  ^/login$
            anonymous: ~

        api:
            pattern:    ^/api/.*
            fos_oauth:  true
            stateless:  true

        main_app:
            pattern:    ^/
            admin-login:
                check_path: /login_check
                login_path: /login
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
            switch_user: true

    access_control:
        - { path: ^/oauth/v2/auth/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authorize, roles: ROLE_API }
        - { path: ^/oauth, roles: ROLE_API }
        - { path: '^/[^/]+/doc/api', roles: [ ROLE_API, ROLE_USER ] }
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/_trans, roles: ROLE_ADMIN }
        - { path: '^/[^/]+/import', roles: [ ROLE_ADMIN, ROLE_IMPORT] }
        - { path: '^/[^/]+/admin', roles: ROLE_ADMIN }
        - { path: '^/[^/]+/ibd/edit', roles: ROLE_CAN_CREATE_CASE }
        - { path: '^/[^/]+/ibd/create', roles: ROLE_CAN_CREATE }
        - { path: '^/[^/]+/ibd/lab', roles: [ ROLE_LAB, ROLE_CAN_CREATE_LAB] }
        - { path: '^/[^/]+/ibd/show', roles: [ ROLE_REGION, ROLE_COUNTRY, ROLE_SITE, ROLE_LAB ] }
        - { path: '^/[^/]+/rota/edit', roles: ROLE_CAN_CREATE_CASE }
        - { path: '^/[^/]+/rota/create', roles: ROLE_CAN_CREATE }
        - { path: '^/[^/]+/rota/lab', roles: [ ROLE_LAB, ROLE_CAN_CREATE_LAB ] }
        - { path: '^/[^/]+/rota/show', roles: [ ROLE_REGION, ROLE_COUNTRY, ROLE_SITE, ROLE_LAB ] }
        - { path: '^/[^/]+', roles: ROLE_USER }
