<?php

namespace NS\SentinelBundle\Repository\Pneumonia;

use NS\SentinelBundle\Entity\Pneumonia\Pneumonia;
use NS\SentinelBundle\Repository\BaseLab;

/**
 * ReferenceLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceLabRepository extends BaseLab
{
    protected $parentClass = Pneumonia::class;
}
