services:
  ns_import.converter.excel_date:
    class: NS\ImportBundle\Converter\ExcelDateConverter
    tags:
      - { name: ns_import.converter }

  ns_import.converter.excel_datetime:
    class: NS\ImportBundle\Converter\ExcelDateTimeConverter
    tags:
      - { name: ns_import.converter }

  ns_import.converter.date.iso:
    class: NS\ImportBundle\Converter\DateTimeValueConverter
    arguments: [ "Y-m-d|" ]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.date.paho1:
    class: NS\ImportBundle\Converter\DateTimeValueConverter
    arguments: [ "d/m/Y|" ]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.date.afr1:
    class: NS\ImportBundle\Converter\DateTimeValueConverter
    arguments: [ "d-M-y|" ]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.date.who:
    class: NS\ImportBundle\Converter\DateTimeValueConverter
    arguments: [ "D M d H:i:s e Y" ]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.date.timestamp:
    class: NS\ImportBundle\Converter\DateTimeValueConverter
    arguments: [ "Y-m-d H:i:s" ]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.date.year_month_day:
    class: NS\ImportBundle\Converter\DateTimeValueConverter
    arguments: [ "Y/m/d|" ]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.date.month_day_year:
    class: NS\ImportBundle\Converter\DateTimeValueConverter
    arguments: [ "m/d/Y|" ]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.time.24_hour_minute_second:
    class: NS\ImportBundle\Converter\TimeValueConverter
    arguments: [ "H:i:s" ]
    calls:
      - [ setDescription, [ '24 Hour format' ]]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.time.24_hour_minute:
    class: NS\ImportBundle\Converter\TimeValueConverter
    arguments: [ "H:i" ]
    calls:
      - [ setDescription, [ '24 Hour format' ]]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.time.12_hour_minute_second:
    class: NS\ImportBundle\Converter\TimeValueConverter
    arguments: [ "h:i:s a" ]
    calls:
      - [ setDescription, [ '12 Hour format a=AM/PM' ]]
    tags:
      - { name: ns_import.converter }

  ns_import.converter.time.12_hour_minute:
    class: NS\ImportBundle\Converter\TimeValueConverter
    arguments: [ "h:i a" ]
    calls:
      - [ setDescription, [ '12 Hour format a=AM/PM' ]]
    tags:
      - { name: ns_import.converter }
