imports:
    - { resource: converters.yml }
    - { resource: forms.yml }
    - { resource: sonata.yml }

parameters:
  ns_import.map.classes: { }

services:
  ns_import.map_column_validator:
    class: NS\ImportBundle\Validators\ImportMapColumnValidator
    arguments: [ "@ns_import.converter.columns" ]
    tags:
      - { name: validator.constraint_validator, alias: map_column_validator }

  ns_import.linker_registry:
    class: NS\ImportBundle\Linker\CaseLinkerRegistry
    arguments: [ {'ns_import.standard_case_linker': "@ns_import.standard_case_linker", 'ns_import.reference_case_linker': "@ns_import.reference_case_linker" }]

  ns_import.standard_case_linker:
    class: NS\ImportBundle\Linker\CaseLinker
    arguments: [ ['site', 'case_id'], 'findBySiteAndCaseId' ]

  ns_import.reference_case_linker:
    class: NS\ImportBundle\Linker\CaseLinker
    arguments: [ ['country','case_id'], 'findByCaseIdAndCheckCountry' ]

  ns_import.reader_factory:
    class: NS\ImportBundle\Reader\ReaderFactory

  ns_import.workqueue:
    class: NS\ImportBundle\Services\WorkQueue
    arguments: [ "@leezy.pheanstalk", "@doctrine.orm.entity_manager", "@ns_import.import_file_creator" ]

  ns_import.twig.import_actions:
    class: NS\ImportBundle\Twig\ImportResultActions
    arguments: [ "@router", "@translator" ]
    tags:
      - { name: twig.extension, alias: ImportResultAction }

  ns_import.import_file_creator:
    class: NS\ImportBundle\Services\ImportFileCreator
    arguments: [ "@vich_uploader.property_mapping_factory" ]

  ns_import.vich.event_listener:
    class: NS\ImportBundle\Vich\EventListener
    tags:
      - { name: kernel.event_listener, event: vich_uploader.post_upload, method: onPostUpload }

  ns_import.batch_worker:
    class: NS\ImportBundle\Importer\ImportBatchWorker
    arguments: [ "@doctrine.orm.entity_manager", "@ns_import.processor", "@ns_import.linker_registry" ]

  ns_import.importer.upload_handler:
    class: NS\ImportBundle\Importer\ImportResultUpdater

  ns_import.vich.directory_namer:
    class: NS\ImportBundle\Vich\DirectoryNamer

  ns_import.converter.columns:
    class: NS\ImportBundle\Converter\ColumnChooser
    arguments: [ "@doctrine.orm.entity_manager", "@doctrine_cache.providers.my_phpfile_cache" ]

  ns_import.form.type.ibd_columns:
    class: NS\ImportBundle\Form\Type\IBDColumnType
    arguments: [ "@ns_import.converter.columns", 'NS\SentinelBundle\Entity\IBD' ]
    tags:
      - { name: form.type, alias: ibd_columns }

  ns_import.form.type.rota_columns:
    class: NS\ImportBundle\Form\Type\RotavirusColumnType
    arguments: [ "@ns_import.converter.columns", 'NS\SentinelBundle\Entity\RotaVirus' ]
    tags:
      - { name: form.type, alias: rota_columns }

  ns_import.services.map_builder:
    class: NS\ImportBundle\Services\MapBuilder
    arguments: [ "@ns_import.reader_factory" ]
    calls:
      - [ setConverterRegistry, [ "@ns_import.converters" ] ]

  ns_import.event.subscriber.doctrine_subscriber:
    class: NS\ImportBundle\Event\Subscriber\DoctrineSubscriber
    tags:
      - { name: kernel.event_subscriber }

  ns_import.processor:
    class: NS\ImportBundle\Importer\ImportProcessor
    arguments: [ "@ns_import.converters", "@doctrine.orm.entity_manager", "@ns_import.linker_registry" ]

  ns_import.array_choice_formatter:
    class: NS\ImportBundle\Formatter\ArrayChoiceFormatter
    arguments: [ "@translator" ]
