parameters:
#    ns_import.example.class: NS\ImportBundle\Example

services:
#    ns_import.example:
#        class: %ns_import.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
