parameters:
#    ns_api.example.class: NS\ApiBundle\Example
    adoy_oauth2.client.class: OAuth2\Client
    ns_api.client.class: NS\ApiBundle\Service\OAuth2Client
    
services:
    ns_api.form.oauth_grant_types:
      class: NS\ApiBundle\Form\Types\OAuthGrantTypes
      tags:
        - { name: form.type, alias: OAuthGrantTypes }

    ns_api.form.text_to_array:
      class: NS\ApiBundle\Form\Type\TextToArray
      tags:
        - { name: form.type, alias: TextToArray }

    ns_api_oauth_server.authorize.form_type:
      class: NS\ApiBundle\Form\Type\AuthorizeFormType
      tags:
        - { name: form.type, alias: api_oauth_server_authorize }
          
    ns_api_oauth_server.authorize.form:
      factory-method: createNamed
      factory-service: form.factory
      class: Symfony\Component\Form\Form
      arguments: [ "@ns_api_oauth_server.authorize.form_type", ns_api_oauth_server_auth ]

    ns_api_oauth_server.authorize.form_handler:
      class: NS\ApiBundle\Form\Handler\AuthorizeFormHandler
      scope: request
      arguments: [ "@ns_api_oauth_server.authorize.form", "@request", "@security.context", "@fos_oauth_server.server" ]

    ns_sentinel.admin.api_client:
        class: NS\ApiBundle\Admin\ClientAdmin
        arguments: [~, NS\ApiBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Sync, label: Api Clients}

    adoy_oauth2.client:
        class: %adoy_oauth2.client.class%
        arguments: [ %oauth2_client_id%, %oauth2_client_secret% ]

    ns_api_client.credentials_client:
        class: %ns_api.client.class%
        arguments:
            - @adoy_oauth2.client
            - %oauth2_auth_endpoint%
            - %oauth2_token_endpoint%
            - %oauth2_redirect_url%
            - client_credentials
            - { client_id: %oauth2_client_id%, client_secret: %oauth2_client_secret% }

    ns_api_client.authorize_client:
        class: %ns_api.client.class%
        arguments: 
            - @adoy_oauth2.client
            - %oauth2_auth_endpoint%
            - %oauth2_token_endpoint%
            - %oauth2_redirect_url%
            - authorization_code
            - { redirect_uri: %oauth2_redirect_url% }
