imports:
  - { resource: forms.yml }
  - { resource: sonata.yml }

parameters:
  adoy_oauth2.client.class: OAuth2\Client
  ns_api.client.class: NS\ApiBundle\Service\OAuth2Client

services:
  ns.api.serializer.array_choice_handler:
    class: NS\ApiBundle\Serializer\ArrayChoiceHandler
    arguments: [ "@translator" ]
    tags:
      - { name: jms_serializer.subscribing_handler }

  oauth2.client:
    class: "%ns_api.client.class%"
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: twig.extension }
