<?php

namespace NS\SentinelBundle\Repository\Meningitis;

use NS\SentinelBundle\Entity\Meningitis\Meningitis;
use NS\SentinelBundle\Repository\BaseLab;

/**
 * ReferenceLab
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceLabRepository extends BaseLab
{
    protected $parentClass = Meningitis::class;
}
